### ISSUE TITLE
assign resource after team has been installed

### ISSUE THREAD

**Issue by mquantin** [UIUCLibrary/teams#110]
I installed Team module (thks for your help)
I start using it. Looks great. Exactly what I need ! :)

Assets created before I installed the team module are not accessible anymore. 
I don't know why, I don't succeed in getting them through the "owner" filter for team.
So they are in no team, so they don't appear anywhere, so I cannot catch them anymore to assign them to a team. 

Moreover I don't succeed in getting team ressource through the API. 
`https://IPadress/api/team-resource?key_identity=myIdentity&key_credential=myCredential`
I get 
`"error": "[Semantical Error] line 0, col 80 near 'id ORDER BY omeka_root.id': Error: Class Teams\\Entity\\TeamResource has no field or association named id"`

I don't know how to catch them ! 
Do you have a way to see "all the items not assign to any team"?

**Comment by alexdryden** [comment]
Thanks for trying it out! I'm really excited to get your feedback. 

Teams aren't part of the REST API because we viewed them more as an internal access control system and didn't see a compelling use case for external API access. If you have a use case for accessing Teams via the REST API I'd be more than happy to look into adding some functionality there. (Edit: I see now there are a few legacy API endpoints. That's probably something I'll get rid of.)

For Items, you can see all Items that are not currently assigned to any Team under the "Trash" link in the admin menu if you are logged in as a global admin. Assets aren't included in there, which was an oversight. I'll add Assets to the Team forms this evening and have a patch ready probably tomorrow afternoon. We were using the module prior to the introduction of Assets, so I overlooked it before now. In the patch you'll be able to add assets via the "owner" method like you tried. Currently, the only way to add assets to a team would be by adding them each individually.

You can also add the query parameter `bypass_team_filter` to any admin view to return all of the results, so `https://your-omeka/admin/asset?bypass_team_filter=true` will return all of the assets. If you only had a few assets, you could edit each of them individually this way to add them to teams.

**Comment by alexdryden** [comment]
I'll add this to the release that is coming out later today, but you can test the fix to the assets on the develop branch now.

**Comment by alexdryden** [comment]
@mquantin the most recent release should address these issues. If you are trying to use the api to query team_resources in the new release, you'll have to add the team id or resource id as a query parameter using `team=` or `resource=` because that table does not have an integer primary key/id.

**Comment by mquantin** [comment]
🤩
Nice!
Thank you a lot. I was not able to work on it Friday. 
I'll try this new release on Monday afternoon. 
I'm really excited to try it out ! 
Of course I'll give you my feedback. 
Once again thank you for this new feature 😃

**Comment by mquantin** [comment]
releaseV3.2.0 (merge #111) fixed the issue.
